### ISSUE TITLE
Whitelister vs json-schema

### ISSUE THREAD

**Issue by miljan-aleksic** [SpireTeam/whitelister#12]
Hi and thank you for sharing your tools with all of us. I am considering if it could be of help for my projects and cannot but think its a problem already solved with json-schema and it wide range of validation tools.

Could you please expose what are the advantages or differences between those two approaches? I am probably missing it :)

**Comment by davidpaulhunt** [comment]
Hi @miljan-aleksic and thanks for your interest in whitelister!

`json-schema` seems like a useful standard and many of its tools are great.

We didn't decide to build whitelister, it came about naturally as we developed our primary platform. So, any competition between json-schema tools and whitelister is purely coincidental.

Additionally, we could have implemented json-schema into whitelister or used an existing tool to replace whitelister. However, the life cycle of our platform is more static than a versioned standard, and not using json-schema gives us the freedom to do things like `transform` and other custom filters. Essentially, we are free to develop whitelister more naturally for our benefit and that of our users.

We also don't need everything that comes with json-schema and we believe only in implementing what you need to reduce potential attack vectors - which is why whitelister is **dependency free**.

As for how it could help you in your projects, it could provide validation and filtering that has been tested over years in a production environment. Again, it's **dependency free** and lightweight.

If you have any more questions, you can reach out to me by email (david@spire.me), and I'm now going to close this issue. Thanks!

Cheers.
\- David
