### ISSUE TITLE
reserved keywords is not allowed

### ISSUE THREAD

**Issue by motss** [SpireTeam/whitelister#7]
The following schema or rules will throw `TypeError: err.toJSON is not a function`:

```js
const wl = require('whitelisted');
const schema = {
  type: 'object',
  attributes: {
    id: { type: 'string', required: true },
    type: { type: 'string', required: true }, // 'type' is not allowed. By changing 'type' to 'idType' does solve the problem.
  },
};

wl(schema, data).catch(err => console.error(err); 
```

**Comment by davidpaulhunt** [comment]
@motss good find!

It seems the problem here is WL losing context of the fact it's iterating through the reserved attributes object. When in that context, WL should treat `type` just like `id` or any other property.

I hope I explained that clearly, I'm sleepy.

I'll work on a fix first thing in the morning 😄

**Comment by davidpaulhunt** [comment]
[Fixed](https://github.com/SpireTeam/whitelister/commit/5616590087229ecc80ad94d6071eb43f8806d59d)
