### ISSUE TITLE
err.toJSON could be a little bit more helpful

### ISSUE THREAD

**Issue by motss** [SpireTeam/whitelister#8]
Almost went nuts about the `err.toJSON is not a function` error message.

After all sort of investigation, found out that if any property is `undefined`, running with a `filterWith` function will produce such error.

It would be very helpful to tell where goes wrong instead of just showing `err.toJSON is not a function`.

```js
const wl = require('whitelister');

const params = {
  firstName: 'John',
  lastName: 'Doe',
  age: 50,
  id: undefined,
};

const schema = {
  type: 'object',
  attributes: {
    age: { type: 'integer', required: true, min: 1 },
    firstName: { type: 'string', required: true, minLength: 1 },
    lastName: { type: 'string', required: true, minLength: 1 },
    id: {
      type: 'string',
      filterWith: val => val.length > 0
        ? /\w{2}\d+/.test(val)
        : true,
    },
  },
};

(async () => {
  try {
    const results = await wl(schema, { ...params });
    console.log(results);
  } catch (e) {
    console.error(e);
  }
})();
```

**Comment by davidpaulhunt** [comment]
@motss sorry it drove you nuts!

The `err.toJSON is not a function` error message, as you probably know, isn't related to the original error. We're probably talking about two separate issues. One, when a TypeError or other standard javascript error, we probably shouldn't immediately push that into the errors array since that array should only contain custom errors.

Two, in your example, an error is being thrown because the `filterWith` function you're providing is calling `.length` on `undefined`. If `params` has the specified property (even if that property's value is `undefined`), WL will filter it with your customer function. This isn't something we tested for, but it's something I should probably address.

- Option 1 is to specify in the documentation that custom `filterWith` functions should check that the value is undefined.
- Option 2 is to make sure that any `undefined` property is ignored and not returned as part of the filtered params.
- Options 3 is to implement option 2 along with a rule like `forceFilterWith` that defaults to false but will always call the customer `filterWith` function if set to true.

I think option 2 would be the best and most expected option.

**Comment by davidpaulhunt** [comment]
[fixed](https://github.com/SpireTeam/whitelister/commit/4d15b9d2dd3e3398943fc3be7de4774a89d914df) in 0.0.5

**Comment by motss** [comment]
@davidpaulhunt Looks great! Thanks for the quick fix! 👍 `whitelister` is awesome once again!
